### ISSUE TITLE
[Enhancement] Handle scopes and opposite

### ISSUE THREAD

**Issue by mathieutu** [sebastiaanluca/laravel-boolean-dates#1]
Hi, @sebastiaanluca!

Cool package, because it handles things we all do in our projects.

Actually I would miss 2 features to be able to replace my implementation with this package: scope, and.. "opposite".

#### Scope
```php
    public function scopeHasAggreed(\Illuminate\Database\Eloquent\Builder $query)
    {
        return $query->whereNotNull('agreed_at');
    }
```

### Opposite
```php
    public function getAvailableAttribute()
    {
        return $this->unavailable_at === null;
    }
```

I've some ideas of how to do it, and I think it should be easy and non breaking to implement it if you want it. I don't have time right now for a PR, but can do it later.

See you,
Matt.

**Comment by sebastiaanluca** [comment]
Love the idea! Do you know if there is a way for us to dynamically create query scopes in Laravel? I should check the source code and see how scopes are loaded and if we can hook into that. Of course we'd have to favor framework- and user-defined scopes before the package's dynamic ones.

In case of opposite values, do you have a proposition how the user could define those? An array with "boolean dates" as keys and their counterparts/opposites as values is my first thought (or reversed), but that might be too verbose. Maybe we should leave that to the user to define if it's too much?

Thanks!

**Comment by mathieutu** [comment]
Hey.

For scopes, it's in the `__call` method of the builder. I think the best way we can do that is by implementing some local macros, as it's done in the `SoftDeletingScope`. But we have to test that the scope doesn't exist, to let the dev overwrite it if s.he wants to.

For opposites, I thought about exactly the same array than `booleanDates` but a sort of `oppositeBooleanDates`, so it's the same to configure, to stay easy and consistent. And a date can be in both arrays:
```php
protected $booleanDates = [
    'disabled' => 'disabled_at',
];
protected $oppositeBooleanDates = [
    'enabled' => 'disabled_at',
];
```

What are your thoughts about that?

**Comment by sebastiaanluca** [comment]
If we can properly hook into the scope building to add dynamic scopes (without overriding any more base methods), but still prevent overriding user-defined scopes, I'm open to a PR or a suggestion. Could use this myself too actually, currently defining boolean field scopes manually. Short on time at the moment so not focusing on new features for this package myself though.

Opposite boolean dates (and perhaps scopes for those too?) would be useful, but I feel we can make that "interface" somewhat cleaner. Just by looking at `'enabled' => 'disabled_at'` and even knowing what it should do or does, I'm still confused about what it will do. That might just be me though 😄
